### ISSUE TITLE
Bug fixing & Improvements

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/datadictionary#77]
@tokland Some notes from our last meeting + some others comments from users. Anyway, we will discuss then on Monday.
- [x] Use v25/26 API.
- [x] Review export to excel feature and fix if needed
- [x] PDF export: reduce font size
- [x] Eliminate default view as an option to a user - instead offer an option to 'reset to default settings' (under Select: add the link)
- [x] Make Organisational view the default view
- [x] Unify list and pop-up schema
- [x] Add lastUpdated, updatedBy, created, createdBy. Not sure everything can be fetched with the API. Therefore, just update what makes sense obviously
- [x] Force reload for tab when schema is changed. In particular Datasets & Programs and Indicator that are currently sharing the schema
- [x] Orgunit/SqlView Settings should be modifiable only by Admin user
- [x] Fix bug: While user is editing My Settings if he changes the key to Organisational or Default, edit panel should hide.
- [x] On popup/edit -> show hand to move rows.
- [x] Readme: Update to changes
- [] Bug: both users were looking at an organisational view which has been persisted - the order of the columns doesn't seem to be persisted? Maybe the cache? [WE COULD NOT REPRODUCE, MORE INFO NEEDED]

**Comment by tokland** [comment]
[9ddb646..5929e96  feature/fixes-and-improvements]

- Review export to excel feature and fix if needed

Now we use the new "buttons" extension instead of TableTools (deprecated), which uses a completely new set of exporting libraries. The "excel" in TT was in fact a T(ab)SV, not a real excel, that's why apps struggled to show it correctly. Buttons/excel creates a normal xlsx file.
- PDF export: reduce font size. Added with buttons. Font size set to 8.
- Eliminate default view as an option to a user - instead offer an option to 'reset to default settings'. DONE. Link under "Select: All | None"
-  Make Organisational view the default view. NODE
- Unify list and pop-up schema: DONE EXCEPT the indicators (de/list -> de/popup), I'll tackle it now, it's a very convoluted code and should be probably refactored at some point.
-  Add lastUpdated, updatedBy, created, createdBy: lastUpdated was already there, added created and createdBy. UpdatedBy is not available.
-  Force reload for tab when schema is changed. In particular Datasets & Programs and Indicator that are currently sharing the schema. DONE
-  Orgunit/SqlView Settings should be modifiable only by Admin user. DONE. Setting input entries have the disable attribute for nor non-admin users.
-  Fix bug: While user is editing My Settings if he changes the key to Organisational or Default, edit panel should hide. DONE
- On popup/edit -> show hand to move rows. DONE
- Readme: Update to changes. DONE
- Bug: both users were looking at an organisational view which has been persisted - the order of the columns doesn't seem to be persisted? Maybe the cache? WE COULD NOT REPRODUCE, MORE INFO NEEDED

**Comment by tokland** [comment]
- [x] Add dimensions to DataElements/popup

**Comment by tokland** [comment]
PR: https://github.com/EyeSeeTea/datadictionary/pull/79

Also changed authority. Use the standard "M_dhis-web-maintenance-appmanager" for user-role "DataDictionary Admin". Reason: Custom authorities are not shown, so there is no way to assign that authority to some other user roles.
